namespace ABIS.LogicBuilder.FlowBuilder.Enums
{
    internal enum VariableCategory : short
    {
        Property,
        Field,
        ArrayIndexer,
        StringKeyIndexer,
        IntegerKeyIndexer,
        BooleanKeyIndexer,
        DateTimeKeyIndexer,
        DateTimeOffsetKeyIndexer,
        DateOnlyKeyIndexer,
        DateKeyIndexer,
        TimeSpanKeyIndexer,
        TimeOnlyKeyIndexer,
        TimeOfDayKeyIndexer,
        GuidKeyIndexer,
        ByteKeyIndexer,
        ShortKeyIndexer,
        LongKeyIndexer,
        FloatKeyIndexer,
        DoubleKeyIndexer,
        DecimalKeyIndexer,
        CharKeyIndexer,
        SByteKeyIndexer,
        UShortKeyIndexer,
        UIntegerKeyIndexer,
        ULongKeyIndexer,
        VariableKeyIndexer,
        VariableArrayIndexer
    }
}
