//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABIS.LogicBuilder.FlowBuilder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ABIS.LogicBuilder.FlowBuilder.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPS Logic Builder.
        /// </summary>
        internal static string applicationNameLogicBuilder {
            get {
                return ResourceManager.GetString("applicationNameLogicBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}({2}).
        /// </summary>
        internal static string constructorToStringFormat {
            get {
                return ResourceManager.GetString("constructorToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string defaultErrorMessage {
            get {
                return ResourceManager.GetString("defaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string enumDescriptionAny {
            get {
                return ResourceManager.GetString("enumDescriptionAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array.
        /// </summary>
        internal static string enumDescriptionArray {
            get {
                return ResourceManager.GetString("enumDescriptionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string enumDescriptionBoolean {
            get {
                return ResourceManager.GetString("enumDescriptionBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string enumDescriptionByte {
            get {
                return ResourceManager.GetString("enumDescriptionByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        internal static string enumDescriptionChar {
            get {
                return ResourceManager.GetString("enumDescriptionChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string enumDescriptionDate {
            get {
                return ResourceManager.GetString("enumDescriptionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string enumDescriptionDateTime {
            get {
                return ResourceManager.GetString("enumDescriptionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTimeOffset.
        /// </summary>
        internal static string enumDescriptionDateTimeOffset {
            get {
                return ResourceManager.GetString("enumDescriptionDateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string enumDescriptionDecimal {
            get {
                return ResourceManager.GetString("enumDescriptionDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string enumDescriptionDouble {
            get {
                return ResourceManager.GetString("enumDescriptionDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float.
        /// </summary>
        internal static string enumDescriptionFloat {
            get {
                return ResourceManager.GetString("enumDescriptionFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Collection.
        /// </summary>
        internal static string enumDescriptionGenericCollection {
            get {
                return ResourceManager.GetString("enumDescriptionGenericCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic List.
        /// </summary>
        internal static string enumDescriptionGenericList {
            get {
                return ResourceManager.GetString("enumDescriptionGenericList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string enumDescriptionGuid {
            get {
                return ResourceManager.GetString("enumDescriptionGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Collection Interface.
        /// </summary>
        internal static string enumDescriptionIGenericCollection {
            get {
                return ResourceManager.GetString("enumDescriptionIGenericCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Enumerable Interface.
        /// </summary>
        internal static string enumDescriptionIGenericEnumerable {
            get {
                return ResourceManager.GetString("enumDescriptionIGenericEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic List Interface.
        /// </summary>
        internal static string enumDescriptionIGenericList {
            get {
                return ResourceManager.GetString("enumDescriptionIGenericList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string enumDescriptionInteger {
            get {
                return ResourceManager.GetString("enumDescriptionInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        internal static string enumDescriptionLong {
            get {
                return ResourceManager.GetString("enumDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Boolean.
        /// </summary>
        internal static string enumDescriptionNullableBoolean {
            get {
                return ResourceManager.GetString("enumDescriptionNullableBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Byte.
        /// </summary>
        internal static string enumDescriptionNullableByte {
            get {
                return ResourceManager.GetString("enumDescriptionNullableByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Char.
        /// </summary>
        internal static string enumDescriptionNullableChar {
            get {
                return ResourceManager.GetString("enumDescriptionNullableChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Date.
        /// </summary>
        internal static string enumDescriptionNullableDate {
            get {
                return ResourceManager.GetString("enumDescriptionNullableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable DateTime.
        /// </summary>
        internal static string enumDescriptionNullableDateTime {
            get {
                return ResourceManager.GetString("enumDescriptionNullableDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable DateTimeOffset.
        /// </summary>
        internal static string enumDescriptionNullableDateTimeOffset {
            get {
                return ResourceManager.GetString("enumDescriptionNullableDateTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Decimal.
        /// </summary>
        internal static string enumDescriptionNullableDecimal {
            get {
                return ResourceManager.GetString("enumDescriptionNullableDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Double.
        /// </summary>
        internal static string enumDescriptionNullableDouble {
            get {
                return ResourceManager.GetString("enumDescriptionNullableDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Float.
        /// </summary>
        internal static string enumDescriptionNullableFloat {
            get {
                return ResourceManager.GetString("enumDescriptionNullableFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Guid.
        /// </summary>
        internal static string enumDescriptionNullableGuid {
            get {
                return ResourceManager.GetString("enumDescriptionNullableGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Integer.
        /// </summary>
        internal static string enumDescriptionNullableInteger {
            get {
                return ResourceManager.GetString("enumDescriptionNullableInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Long.
        /// </summary>
        internal static string enumDescriptionNullableLong {
            get {
                return ResourceManager.GetString("enumDescriptionNullableLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable SByte.
        /// </summary>
        internal static string enumDescriptionNullableSByte {
            get {
                return ResourceManager.GetString("enumDescriptionNullableSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable Short.
        /// </summary>
        internal static string enumDescriptionNullableShort {
            get {
                return ResourceManager.GetString("enumDescriptionNullableShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable TimeOfDay.
        /// </summary>
        internal static string enumDescriptionNullableTimeOfDay {
            get {
                return ResourceManager.GetString("enumDescriptionNullableTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable TimeSpan.
        /// </summary>
        internal static string enumDescriptionNullableTimeSpan {
            get {
                return ResourceManager.GetString("enumDescriptionNullableTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable UInteger.
        /// </summary>
        internal static string enumDescriptionNullableUInteger {
            get {
                return ResourceManager.GetString("enumDescriptionNullableUInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable ULong.
        /// </summary>
        internal static string enumDescriptionNullableULong {
            get {
                return ResourceManager.GetString("enumDescriptionNullableULong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullable UShort.
        /// </summary>
        internal static string enumDescriptionNullableUShort {
            get {
                return ResourceManager.GetString("enumDescriptionNullableUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Byte.
        /// </summary>
        internal static string enumDescriptionSByte {
            get {
                return ResourceManager.GetString("enumDescriptionSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        internal static string enumDescriptionShort {
            get {
                return ResourceManager.GetString("enumDescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string enumDescriptionString {
            get {
                return ResourceManager.GetString("enumDescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeOfDay.
        /// </summary>
        internal static string enumDescriptionTimeOfDay {
            get {
                return ResourceManager.GetString("enumDescriptionTimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeSpan.
        /// </summary>
        internal static string enumDescriptionTimeSpan {
            get {
                return ResourceManager.GetString("enumDescriptionTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned Integer.
        /// </summary>
        internal static string enumDescriptionUInteger {
            get {
                return ResourceManager.GetString("enumDescriptionUInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned Long.
        /// </summary>
        internal static string enumDescriptionULong {
            get {
                return ResourceManager.GetString("enumDescriptionULong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned Short.
        /// </summary>
        internal static string enumDescriptionUShort {
            get {
                return ResourceManager.GetString("enumDescriptionUShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Argument {0}..
        /// </summary>
        internal static string invalidArgumentTextFormat {
            get {
                return ResourceManager.GetString("invalidArgumentTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Of {1}.
        /// </summary>
        internal static string listDescriptionFormat {
            get {
                return ResourceManager.GetString("listDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Of{1}: {2}.
        /// </summary>
        internal static string listParameterTypeNameFormat {
            get {
                return ResourceManager.GetString("listParameterTypeNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not implemented in {0}..
        /// </summary>
        internal static string notImplementedMessageFormat {
            get {
                return ResourceManager.GetString("notImplementedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string parameterTypeNameFormat2 {
            get {
                return ResourceManager.GetString("parameterTypeNameFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string spaceString {
            get {
                return ResourceManager.GetString("spaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string underscore {
            get {
                return ResourceManager.GetString("underscore", resourceCulture);
            }
        }
    }
}
